### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by rossbeazley** [carlosedp/minecraft-server-arm64#1]
hello, having deployed your docker image on an odroidc2 im getting the following exception

[17:25:28] [Server thread/INFO]: Starting minecraft server version 1.7.10
[17:25:45] [Server thread/ERROR]: Encountered an unexpected exception
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_172]
	at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_172]
	at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_172]
	at java.awt.Frame.<init>(Frame.java:385) ~[?:1.8.0_172]
	at javax.swing.JFrame.<init>(JFrame.java:189) ~[?:1.8.0_172]
	at t.p.a(SourceFile:284) ~[p.class:?]
	at o.b.a(SourceFile:183) ~[b.class:?]
	at A.e.a(SourceFile:50) ~[e.class:?]
	at de.maggicraft.ism.h.a(SourceFile:56) ~[h.class:?]
	at de.maggicraft.ism.ISMMain.a(SourceFile:177) ~[ISMMain.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) ~[Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:25:45] [Server thread/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2019-03-01_17.25.45-server.txt

with the following in the crash report

---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version 3.14.79-117
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1738457704 bytes (1657 MB) / 2075918336 bytes (1979 MB) up to 2075918336 bytes (1979 MB)
	JVM Flags: 3 total; -XX:+UseG1GC -Xms2G -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	doggytalents{1.14.2.308} [Doggy Talents] (DoggyTalents-1.7.10-1.14.2.308-universal.jar) 
	UCE	ism{2.5 MC-1.7.10} [Instant Structures Mod (ISM)] (ism-2.5 MC-1.7.10.jar) 
	UCH	dna948{1.35} [The Last Sword You Will Ever Need Mod] (The-Last-Sword-You-Will-Ever-Need-Mod-1.7.10.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by carlosedp** [comment]
Maybe because Odroid C2 has 2GB of Ram and the Minecraft instance was started with 2GB Heap (`-Xms2G -Xmx2G`).

Try to change this parameter in the environment variable `MEMORY`.

If using Docker, use `-e MEMORY=1G` or in Docker-compose, something like:

```
  minecraft:
    image: carlosedp/minecraft-server:arm64
    restart: unless-stopped
    network_mode: host
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/carlosedp/mc-data:/data
    environment:
      - MEMORY=1G
      - ALLOW_FLIGHT=TRUE
```

**Comment by rossbeazley** [comment]
thanks, ill give that a go and report back, im using k8s so here is the yaml ill use

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-data
spec:
  capacity:
    storage: 30Gi 
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.4
    path: "/nfs/mc-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla
spec:
  type: NodePort
  ports:
  - port: 25565
    nodePort: 30303
  selector:
    app: mc-vanilla
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      containers:
      - image: carlosedp/minecraft-server:arm64
        name: mc-vanilla
        env:
          # Use secret in real usage
        - name: EULA
          value: "true"
        - name: VERSION
          value: "1.7.10"
        - name: TYPE
          value: FORGE
        - name: MEMORY
          value: "1G"
        ports:
        - containerPort: 25565
          name: main
        volumeMounts:
        - name: mc-data
          mountPath: /data
          readOnly: false
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "3.0"
          requests:
            memory: "1.5Gi"
            cpu: "2.0"
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: mc-data
```
